controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

index:
    path: /
    controller: App\Controller\IndexController::index

create:
    path: /create
    controller: App\Controller\crud\CreateController::create

read:
    path: /read
    controller: App\Controller\crud\ReadController::read

delete:
    path: /delete/{id}
    controller: App\Controller\crud\DeleteController::delete